"""empty message

Revision ID: 441f66454c4d
Revises: d10397808819
Create Date: 2024-07-30 13:03:50.932469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '441f66454c4d'
down_revision: Union[str, None] = 'd10397808819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_achievements', 'date_on',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата выдачи достижения',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_achievements', 'date_on',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата выдачи достижения',
               existing_nullable=False)
    # ### end Alembic commands ###
